Update custom_field.json
Update default = 0 for Date fields due to db error in update.

_mysql_exceptions.OperationalError: (1067, "Invalid default value for 'stuffing_date'")